In [5]:
import numpy as np
#Combining a 1D and 2D array 
d1=np.array([1,2,3,4])
d2=np.array([[5,6,7,8],[9,10,11,12]])
res=np.concatenate((d1.reshape(1, -1), d2))
print("D1:",d1)
print("D2:",d2)
print("Resultant:\n",res)

D1: [1 2 3 4]
D2: [[ 5  6  7  8]
 [ 9 10 11 12]]
Resultant:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
#Flattening an array 
res=d2.reshape(-1)
print("Org:\n",d2)
print("Flattened:\n",res)

Org:
 [[ 5  6  7  8]
 [ 9 10 11 12]]
Flattened:
 [ 5  6  7  8  9 10 11 12]


In [10]:
#Reversing an numpy array
print("Unreversed:",d1)
i=0;j=len(d1)-1
while(i<=j):
    temp=d1[i]
    d1[i]=d1[j]
    d1[j]=temp
    i+=1
    j-=1
print("Reversed:",d1)


Unreversed: [1 2 3 4]
Reversed: [4 3 2 1]


In [45]:
#4
#Getting maximum minimum values
maxE=np.max(d1)
minE=np.min(d1)
print("Maximum:",maxE)
print("Minimum:",minE)
#Finding rows and columns of an array
x,y=np.shape(d2)
print("Rows:",x,"Cols:",y)
#Getting each element from 2D array
print("D2:")
for x in d2:
    for y in x:
        print(y,end='\t')
    print()
#Accessing specific elements
print(d2[0,1])
print(d2[1,1])
#Getting sum of values of 2D array using for loops
sum=0
for x in d2:
    for y in x:
        sum+=y
print("Sum of d2's elements:",sum)

Maximum: 4
Minimum: 1
Rows: 2 Cols: 4
D2:
5	6	7	8	
9	10	11	12	
6
10
Sum of d2's elements: 68


In [22]:
#Arithmetic operations on arrays
sum=d1+2
sub=d1-2
mul=d1*3
div=d1/3
print("Original:",d1)
print("Addition:",sum)
print("Subtraction:",sub)
print("Multiplication:",mul)
print("Division:",div)

Original: [4 3 2 1]
Addition: [6 5 4 3]
Subtraction: [ 2  1  0 -1]
Multiplication: [12  9  6  3]
Division: [1.33333333 1.         0.66666667 0.33333333]


In [27]:
#Iterating 3D array
d3=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(d3.shape)
for x in d3:
    for y in x:
        for z in y:
            print(z,end=' ')
print()
for x in np.nditer(d3):
    print(x,end=' ')

(2, 2, 3)
1 2 3 4 5 6 7 8 9 10 11 12 
1 2 3 4 5 6 7 8 9 10 11 12 

In [51]:
#6
# create a numpy 1d-arrays
arr1 = np.array([3, 4,3]) 
arr2 = np.array([1, 0,3]) 
# find average of NumPy arrays avg = (arr1 + arr2) / 2 
# print("Average of NumPy arrays:\n", avg) ->
# Calculate average mean median mode values of two NumPy 2d-arrays
avg=(arr1+arr2)/2
print("Average of two arrays:",avg)
comb=np.concatenate((arr1,arr2))
print("Mean:",np.mean(comb))
print("Median:",np.median(comb))
#Finding mode 
max_count = 0
mode = None
for i in range(len(comb)):
    count = 0
    for j in range(len(comb)):
        if comb[i] == comb[j]:
            count += 1
    if count > max_count:
        max_count = count
        mode = comb[i]
print("Mode:", mode)


Average of two arrays: [2. 2. 3.]
Mean: 2.3333333333333335
Median: 3.0
Mode: 3
