In [ ]:
import numpy as np
#1Replacing nan with 0
ar=np.array([[6,-8,73,-110],
            [np.nan,-8,4,2],
            [4,5,np.nan,3]])
ar=np.nan_to_num(ar,nan=0)
print("After removing nan:",ar)
#Interchanging rows and columns
ar[[0,1]]=ar[[1,0]]
ar[[1,2]]=ar[[2,1]]
ar[:,[0,1]]=ar[:,[1,0]]
ar[:,[1,2]]=ar[:,[2,1]]
print("After replacing rows and columns\n:",ar)


[[   6.   -8.   73. -110.]
 [   0.   -8.    4.    2.]
 [   4.    5.    0.    3.]]
[[   0.   -8.    4.    2.]
 [   4.    5.    0.    3.]
 [   6.   -8.   73. -110.]]


In [10]:
#2Moving axes of 3D array
arr=np.array([
    [[1,2],[4,5],[7,8]],
    [[11,12],[14,15],[17,18]],
    [[21,22],[24,25],[27,28]]
])
print("Original:",arr.shape)
arr=arr.transpose()
print("Transposed:",arr.shape)
arr=np.moveaxis(arr,0,1)
print("Moved Axes:",arr.shape)

Original: (3, 3, 2)
Transposed: (2, 3, 3)
Moved Axes: (3, 2, 3)


In [20]:
#3 Replacing NaN values with column mean
nums=np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]])
colAvg=np.nanmean(nums,axis=0)
indx=np.where(np.isnan(nums))
nums[indx] = np.take(colAvg, indx[1])
print(nums)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [24]:
#4 Replacing -ve values with zero
org=np.array([1,-2,-3,4,2])
#2 methods , conditonal statements or np.maximum
o1=np.where(org < 0,0,org)
o2=np.maximum(org,0)
print(org)
print(o1)
print(o2)

[ 1 -2 -3  4  2]
[1 0 0 4 2]
[1 0 0 4 2]
