In [6]:
import numpy as np
#1
#Creating numpy array and performing operations
arr=np.array([1,2,3,4,5,6])
arr=arr.reshape((2,3))
print("Shape:",arr.shape)
rows,cols=arr.shape
print("Rows:",rows,"Cols:",cols)
print("Datatype:",type(arr[0][0]))
print("Itemsize:",arr.itemsize)

Shape: (2, 3)
Rows: 2 Cols: 3
Datatype: <class 'numpy.int64'>
Itemsize: 8


In [8]:
#Creating 3x3 array of 9
arr1=np.full((3,3),9)
print(arr1)
arr2=np.arange(25,125,10)
print(arr2)

[[9 9 9]
 [9 9 9]
 [9 9 9]]
[ 25  35  45  55  65  75  85  95 105 115]


In [15]:
#Creating an array from list and extracting even rows and odd columns
lt=[[1,2,3],[3,4,5],[7,6,1],[9,8,0]]
arr3=np.array(lt)
print(arr3)
rows=arr3[::2,:]
cols=arr3[:,1::2]
print("Even rows:\n",rows)
print("Odd cols:\n",cols)

[[1 2 3]
 [3 4 5]
 [7 6 1]
 [9 8 0]]
Even rows:
 [[1 2 3]
 [7 6 1]]
Odd cols:
 [[2]
 [4]
 [6]
 [8]]


In [ ]:
#Reversing array
print("Original:",arr2)
rev=arr2[::-1]
print("Reversed:",rev)
#Accessing element in (4x4x3) 3D Array
threeD=np.array([
    [[1,2,3],[0,4,1],[4,7,2],[10,1,4]],
    [[5,6,7],[2,1,8],[6,4,8],[7,3,6]],
    [[1,6,9],[5,6,3],[0,2,0],[2,1,2]],
    [[0,9,0],[11,5,20],[8,5,5],[1,0,4]]
])
print(threeD.shape)
print("Element in second set,first row and last column:",threeD[1,0,-1])


Original: [ 25  35  45  55  65  75  85  95 105 115]
Reversed: [115 105  95  85  75  65  55  45  35  25]
(4, 4, 3)
Element in second set,first row and last column: 7


In [33]:
#Replacing odd numbers with -1
arr4=np.array([[23, 56, 78, 93], [71, 82,13, 24]])
arr4[arr4 % 2 !=0]=-1
print("Replaced:\n",arr4)
#Getting indices of non zero items
arr5=np.array([1, 0, 2, 0, 3, 0, 4])
indices=np.where(arr5 > 0)
print("Non Zero value indexes:",indices[0])

Replaced:
 [[-1 56 78 -1]
 [-1 82 -1 24]]
Non Zero value indexes: [0 2 4 6]


In [35]:
#Performing maths operations on two arrays
A = np.array([
    [2, 4, 6],
    [1, 3, 5]
])
B = np.array([
    [10, 20, 30],
    [5, 15, 25]
])
print("Addition:\n",A+B)
print("Multiplication:\n",A*B)

Addition:
 [[12 24 36]
 [ 6 18 30]]
Multiplication:
 [[ 20  80 180]
 [  5  45 125]]


In [ ]:
#Dot product
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])
res=arr1.dot(arr2)
print("Dot product:\n",res)

Dot product:
 1875
